### ISSUE TITLE
Ternary operators should not be nested.RSPEC-3358

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-static-analysis#51]
> Just because you can do something, doesn’t mean you should, and that’s the case with nested ternary operations. Nesting ternary operators results in the kind of code that may seem clear as day when you write it, but six months later will leave maintainers (or worse - future you) scratching their heads and cursing.
> 
> Instead, err on the side of clarity, and use another line to express the nested operation as a separate statement.

Noncompliant Code Example

```java

public String getReadableStatus(Job j) {
  return j.isRunning() ? "Running" : j.hasErrors() ? "Failed" : "Succeeded";  // Noncompliant
}

```

Compliant Solution

```java

public String getReadableStatus(Job j) {
  if (j.isRunning()) {
    return "Running";
  }
  return j.hasErrors() ? "Failed" : "Succeeded";
}

```

https://rules.sonarsource.com/java/RSPEC-3358

**Comment by pstreef** [comment]
I would like to pick this up. Since the issue is a year old I guess there is not much of a hurry and I can try out creating an actual recipe.

**Comment by yeikel** [comment]
> I would like to pick this up. Since the issue is a year old I guess there is not much of a hurry and I can try out creating an actual recipe.

Please go for it

@timtebeek Might be able to assign it to you, but you can get a head start

**Comment by timtebeek** [comment]
Thanks for the tag @yeikel and thanks for the offer @pstreef ! Let us know if you'd need any help with this.

In the past it's worked best to first get the boundaries straight with a draft PR that only adds tests.
It's a nice exercise in adversarial thinking on what code patterns in the wild might trip up the recipe.

With recipe development [the TreeVisitingPrinter might help](https://docs.openrewrite.org/concepts-explanations/tree-visiting-printer) explain what elements are available in the source tree.
Then from there you might want to look at [JavaTemplate to generate new code constructs](https://docs.openrewrite.org/concepts-explanations/javatemplate).

There could be some tricky aspects with regards to type attribution on the new code elements with JavaTemplate though, so that might not be the absolute best fit here. If you find that's troublesome we also support creating new tree elements using constructors, which are easier to type attribute.

**Comment by pstreef** [comment]
@timtebeek 

Help is definitely welcome as I'm flailing about a bit with the implementation. However, messing around is a good way to learn, and I'm already starting to get somewhere.

Finding a nested ternary is quite easy, but then the challenge is how to actually rewrite something. The samples are relatively simple in comparison to this problem which I (of course) underestimated starting out.

I do have a bunch of tests already set up which I can share, and a start of something that might look like an implementation. I'm doubting to take non returning statements into consideration at all, because that might complicate things by a lot. (at least for starters).

some problems I have are:

I want to return multiple statements:
```
return "a".equals(a) ? "a" : "b".equals(b) ? "b" : "nope";
```
should become
```
if("a".equals(a)){
                    return "a";
                  }
                  return  "b".equals(b) ? "b" : "nope";
```
initially I started out with a ternaryVisitor, but those are not statements but expressions, so I'm missing the return part.

using a returnVisitor I can find these nicely, and if I return a block with multiple statements I can almost make it work, but I obviously don't want the extra brackets.

I can also make it work with an if/else setup, but the else does not make much sense if the result is returned in the if.

So I think I should look for the firstEnclosing(Block.class) and then somehow replace that.

Maybe you can have a look at my implementation and give some hints?

**Comment by timtebeek** [comment]
Fixed in 
- https://github.com/openrewrite/rewrite-static-analysis/pull/93
