### ISSUE TITLE
ReplaceLambdaWithMethodReference leads to ambiguous reference

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-static-analysis#96]
I ran [ReplaceLambdaWithMethodReference](https://public.moderne.io/recipes/org.openrewrite.java.cleanup.ReplaceLambdaWithMethodReference) on https://github.com/openrewrite/rewrite-java-security/pull/80 which replaced the recipe constructor call in [FileConstructorFixVisitorTest](https://github.com/openrewrite/rewrite-java-security/blob/v1.21.0/src/test/java/org/openrewrite/java/security/internal/FileConstructorFixVisitorTest.java#L28) with a lambda. That change leads to ambiguity with the [multiple `toRecipe` methods](https://github.com/openrewrite/rewrite/blob/v7.35.0/rewrite-test/src/main/java/org/openrewrite/test/RewriteTest.java#L48) in RewriteTest.

```
/home/runner/work/rewrite-java-security/rewrite-java-security/src/test/java/org/openrewrite/java/security/internal/FileConstructorFixVisitorTest.java:28: error: reference to toRecipe is ambiguous
        spec.recipe(RewriteTest.toRecipe(FileConstructorFixVisitor::new));
                               ^
  both method toRecipe(Supplier<TreeVisitor<?,ExecutionContext>>) in RewriteTest and method toRecipe(Function<Recipe,TreeVisitor<?,ExecutionContext>>) in RewriteTest match
/home/runner/work/rewrite-java-security/rewrite-java-security/src/test/java/org/openrewrite/java/security/internal/StringToFileConstructorVisitorTest.java:27: error: reference to toRecipe is ambiguous
        spec.recipe(RewriteTest.toRecipe(StringToFileConstructorVisitor::new));
                               ^
  both method toRecipe(Supplier<TreeVisitor<?,ExecutionContext>>) in RewriteTest and method toRecipe(Function<Recipe,TreeVisitor<?,ExecutionContext>>) in RewriteTest match
```

In such cases where there might be ambiguity, the recipe should not make changes.

**Comment by jbessels** [comment]
I've noticed that the choosen 'solution' was to check if: ReplaceLambdaWithMethodReference should not replace ambiguous references

Rather then: In my case .map(i -> i.toString()) was converted to .map(Integer::toString) which led to ambiguity. BUT manually changing this into .map(String::valueOf) did work. After all there is more then one way to convert an integer into a string. There might be other situations where a 'smart' change can be applied.

The change it seems has been made by a contributor to OpenRewrite,  srmalkan.  Could his code by extended so that the lambda could be  rewritten to  .map(String::valueOf) . This would be a more optimized situation wrt Lamba's. 

Any way in my case I could remove two <exclusion> tags as the files are no longer changed.

**Comment by knutwannheden** [comment]
@jbessels For the lambda `(integer i) -> i.toString()` to be safely converted to the `String::valueOf` method reference, we would require nullability information on `i`. Because `String::valueOf` will convert a `null` to the String value `"null"`, whereas the original would end up throwing a `NullPointerException`.

Given the semantical difference, I think we would need the nullability information to be able to do this safely. This is something we don't yet have, but many recipes could indeed benefit from this.
